FROM ubuntu:latest
FROM python:3.6-onbuild
VOLUME ["/pirates_volume"]
RUN  apt-get update &&apt-get upgrade -y&& apt-get install python-pip -y
RUN pip install --upgrade pip
RUN pip install scrapy
ADD . /pirates_challenge
WORKDIR /pirates_challenge
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 80
CMD ["scrapy", "crawl", "correios", "-o", "/pirates_volume/data.json"]