FORMDATA_UF = "UF"
FORMDATA_LOCALIDADE = "Localidade"
FORMDATA_ALL_VALUES = "**"

FORMNAME_PROXIMA = "Proxima"
FORMNAME_GERAL = "Geral"

ITEM_FIELD_ZIP = 'zip'
ITEM_FIELD_LOCATION = 'location'
ITEM_FIELD_RECORD = 'record'
ITEM_FIELD_UF = 'uf'
